# configurations of app, like address, ...
app:
  address: localhost:8080
# configurations of database, like mysql, redis, ...
database:
  mysql:
    username: root
    password: m1998526
    address: localhost:3306
    database: mini_douyin