# configurations of app, like address, ...
app:
  address: http://10.28.171.163:8080
# configurations of database, like mysql, redis, ...
database:
  mysql:
    username: root
    password: 123123
    address: localhost:3306
    database: mini-douyin